### ISSUE TITLE
GUI in one window

### ISSUE THREAD

**Issue by bricaud** [SFI-Visual-Intelligence/AI-exhibition#5]
We got some feedback to make each demo in a single window. It would reduce the risk to hack the demo when some windows are closed while other open.

One solution may be to use [https://pyscript.net/](https://pyscript.net/) in order to make all the demos run in the browser.

Another popular solution in ML now is [Gradio](https://gradio.app/) but I can't figure out if it can work with video streaming. It seems not (not yet).

**Comment by c-salomonsen** [comment]
Per pyscript, as it stands there does not seem to be [backend support for pygame in a browser using pyscript](https://stackoverflow.com/questions/72181600/is-it-possible-to-run-game-made-with-pygame-on-browser-using-pyscript), which affect one of the demos ([pyodide support for pygame](https://github.com/pyodide/pyodide/issues/289)). As per the demos only requiring a video or camera feed, I do think this would be possible to implement quite easily.

As per gradio I do not see anyone having any experience using it in conjunction with pygame. Per the demos using the cameras, I also haven't seen any documentation with using a live video feed or backend support for taking images.

I do think using pyscript could work very well for the demos not requiring pygame, although that of course does not fulfill the requirements for all the demos. I wonder if there is a possibility to use some [html rendering inside pyqt5](https://stackoverflow.com/questions/37754138/how-to-render-html-with-pyqt5s-qwebengineview) as also pygame perhaps has [limited support for pyqt5](https://stackoverflow.com/questions/60239642/confusion-transferring-pyopengl-from-pygame-to-pyqt5)

**Comment by c-salomonsen** [comment]
Additionally: Rendering python in a browser is not recommended and especially with pygame, I found something suggesting [compiling to javascript, then rendering](https://stackoverflow.com/questions/8452927/is-it-possible-to-run-pygame-or-pyglet-in-a-browser) although compiling machine learning code to javascript might be a too large digression.

**Comment by pmp-p** [comment]
> Rendering python in a browser is not recommended and especially with pygame

That is certainly not true when using sane resolutions for 2D canvas. Pygame can run well in browser, it can also run as a [script engine](https://pygame-web.github.io/showroom/pygame-scripts/org.pygame.touchpong.html). For 3D in browser it is preferable to use Panda3D or Harfang3D.

The only limitation to pyscript is that the engine (pyodide) used by default is not linked to SDL2 or WebGL2 for size reason. But i don't see why you could not use a custom pyodide or cpython (3.11+) build with it or just ask for it https://github.com/pyodide/pyodide/issues/289#issuecomment-1279942065.
