### ISSUE TITLE
crash when calling opencv

### ISSUE THREAD

**Issue by bricaud** [SFI-Visual-Intelligence/AI-exhibition#7]
The emotion detection crashes from time to time
Here is a screenshot:
![image](https://github.com/SFI-Visual-Intelligence/AI-exhibition/assets/6340337/2f2ebcb4-873c-40ab-bc84-a194d846967a)

It looks like this is the line where it happens:

https://github.com/SFI-Visual-Intelligence/AI-exhibition/blob/ab118527cfc774e0685b734fbd569c1c35be4b15/computer-vision/face-detection-without-names/face_detector.py#L78C12-L78C12

What I suspect is that sometimes the the webcam sends an empty frame and the process crashes. If we add a "try:" before this line and then an "except:" where we jump back to the beginning of the loop to get a new image with "continue" , it could do the trick.
Something like:
```
try:
   faces,gray = detection.get_faces(img, face_detector) 
except:
   continue
```

**Comment by Kuttner** [comment]
Implemented in main.
